namespace HrProject.Shared.Models;

public sealed record PreEmployeeDto(
    long Id,
    string? SourceSystem,
    string? SourceReferenceId,
    string EmployeeCode,
    string Title,
    string FirstNameTh,
    string LastNameTh,
    string FullNameEn,
    string Nickname,
    string Email,
    string LotusNotesEmail,
    string PersonalMobile,
    string Company,
    string BusinessUnit,
    string Department,
    string Position,
    DateOnly? StartDate,
    string SupervisorName,
    string LeaveApproverName,
    string EmploymentType,
    string WorkLocation,
    string Status,
    string? ValidationMessage,
    long? CreatedEmployeeId,
    string? ImportedBy,
    string? ImportedByName,
    DateTimeOffset? ImportedAt,
    string? ReviewedBy,
    string? ReviewedByName,
    DateTimeOffset? ReviewedAt,
    string CreatedBy,
    string CreatedByName,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string? ConvertedBy,
    string? ConvertedByName,
    DateTimeOffset? ConvertedAt,
    Employee EmployeeData);

public sealed record SavePreEmployeeRequest(
    string? SourceSystem,
    string? SourceReferenceId,
    string? EmployeeCode,
    string? Title,
    string? FirstNameTh,
    string? LastNameTh,
    string? FullNameEn,
    string? Nickname,
    string? Email,
    string? LotusNotesEmail,
    string? PersonalMobile,
    string? Company,
    string? BusinessUnit,
    string? Department,
    string? Position,
    DateOnly? StartDate,
    string? SupervisorName,
    string? LeaveApproverName,
    string? EmploymentType,
    string? WorkLocation,
    Employee? EmployeeData = null);

public sealed record ConvertPreEmployeeResult(long PreEmployeeId, long EmployeeId, string EmployeeCode);
