CREATE TABLE IF NOT EXISTS public.attendance_calendar_events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  VARCHAR(50) NOT NULL,
    event_date   DATE NOT NULL,
    event_type   VARCHAR(30) NOT NULL,
    start_time   TIME NOT NULL,
    end_time     TIME NOT NULL,
    title        VARCHAR(200),
    details      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_attendance_calendar_event_type
        CHECK (event_type IN ('WORK_FROM_HOME', 'CUSTOMER_VISIT', 'OTHER')),
    CONSTRAINT ck_attendance_calendar_event_time
        CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS ix_attendance_calendar_events_employee_date
    ON public.attendance_calendar_events(employee_id, event_date, start_time);

CREATE OR REPLACE FUNCTION public.queue_attendance_recalculation_from_calendar_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        INSERT INTO public.attendance_recalculation_queue(employee_id, work_date, reason)
        VALUES (OLD.employee_id, OLD.event_date, 'ATTENDANCE_EVENT_CHANGED')
        ON CONFLICT (employee_id, work_date) DO UPDATE
        SET reason = EXCLUDED.reason, requested_at = CURRENT_TIMESTAMP,
            attempts = 0, last_error = NULL;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        INSERT INTO public.attendance_recalculation_queue(employee_id, work_date, reason)
        VALUES (NEW.employee_id, NEW.event_date, 'ATTENDANCE_EVENT_CHANGED')
        ON CONFLICT (employee_id, work_date) DO UPDATE
        SET reason = EXCLUDED.reason, requested_at = CURRENT_TIMESTAMP,
            attempts = 0, last_error = NULL;
    END IF;

    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS trg_attendance_calendar_event_recalculation
    ON public.attendance_calendar_events;
CREATE TRIGGER trg_attendance_calendar_event_recalculation
AFTER INSERT OR UPDATE OR DELETE ON public.attendance_calendar_events
FOR EACH ROW EXECUTE FUNCTION public.queue_attendance_recalculation_from_calendar_event();
