CREATE TABLE IF NOT EXISTS public.work_calendar_document_templates
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_type   VARCHAR(30) NOT NULL,
    template_name   VARCHAR(200) NOT NULL,
    version_no      INTEGER NOT NULL,
    is_published    BOOLEAN NOT NULL DEFAULT FALSE,
    settings        JSONB NOT NULL,
    created_by      VARCHAR(50) NOT NULL,
    created_by_name VARCHAR(200) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_work_calendar_template_type
        CHECK (template_type IN ('PUBLIC_HOLIDAY', 'WORKING_SATURDAY')),
    CONSTRAINT ck_work_calendar_template_version CHECK (version_no > 0),
    CONSTRAINT ux_work_calendar_template_version UNIQUE(template_type, version_no)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_work_calendar_template_published
    ON public.work_calendar_document_templates(template_type)
    WHERE is_published = TRUE;

INSERT INTO public.work_calendar_document_templates
    (template_type, template_name, version_no, is_published, settings, created_by, created_by_name)
SELECT 'PUBLIC_HOLIDAY', 'Template วันหยุดมาตรฐาน', 1, TRUE,
       '{
          "headerBandColor":"#f31322","accentColor":"#001b80","titleColor":"#111827",
          "showLogo":true,"logoPosition":"RIGHT","titleAlignment":"CENTER",
          "titleThai":"ประกาศวันหยุดตามประเพณี ประจำปี {{year_th}}",
          "titleEnglish":"Announcement : Public Holidays for year {{year_en}}",
          "showEnglishTitle":true,"introText":"","policyText":"",
          "footerThai":"บริษัท เอสไอเอส ดิสทริบิวชั่น (ประเทศไทย) จำกัด (มหาชน) | เลขที่ 9 อาคารภคินท์ ชั้น 9 ห้องเลขที่ 901 ถนนรัชดาภิเษก แขวงดินแดง เขตดินแดง กรุงเทพฯ 10400 โทรศัพท์ 02-020-3000",
          "footerEnglish":"SIS DISTRIBUTION (THAILAND) PUBLIC COMPANY LIMITED | 9 Pakin Building, 9th Floor, Room No.901, Ratchadaphisek Road, Din Daeng, Bangkok 10400 Tel: +662-020-3000",
          "showFooter":true,"pageMarginMm":17,"baseFontSizePt":9.2,"listSpacingMm":2.2
        }'::jsonb,
       'SYSTEM', 'System'
WHERE NOT EXISTS
(
    SELECT 1 FROM public.work_calendar_document_templates WHERE template_type = 'PUBLIC_HOLIDAY'
);

INSERT INTO public.work_calendar_document_templates
    (template_type, template_name, version_no, is_published, settings, created_by, created_by_name)
SELECT 'WORKING_SATURDAY', 'Template วันเสาร์ทำงานมาตรฐาน', 1, TRUE,
       '{
          "headerBandColor":"#f31322","accentColor":"#001b80","titleColor":"#111827",
          "showLogo":true,"logoPosition":"RIGHT","titleAlignment":"CENTER",
          "titleThai":"ประกาศ|วันเสาร์ทำงานประจำปี พ.ศ. {{year_th}}",
          "titleEnglish":"","showEnglishTitle":false,"introText":"",
          "policyText":"เวลาทำงาน 09:00 - 17:00 น. และพักกลางวัน 12:00 - 13:00 น.|วันเสาร์ที่ไม่ปรากฏในประกาศนี้ถือเป็นวันหยุดประจำสัปดาห์",
          "footerThai":"บริษัท เอสไอเอส ดิสทริบิวชั่น (ประเทศไทย) จำกัด (มหาชน) | เลขที่ 9 อาคารภคินท์ ชั้น 9 ห้องเลขที่ 901 ถนนรัชดาภิเษก แขวงดินแดง เขตดินแดง กรุงเทพฯ 10400 โทรศัพท์ 02-020-3000",
          "footerEnglish":"SIS DISTRIBUTION (THAILAND) PUBLIC COMPANY LIMITED | 9 Pakin Building, 9th Floor, Room No.901, Ratchadaphisek Road, Din Daeng, Bangkok 10400 Tel: +662-020-3000",
          "showFooter":true,"pageMarginMm":17,"baseFontSizePt":13,"listSpacingMm":2.3
        }'::jsonb,
       'SYSTEM', 'System'
WHERE NOT EXISTS
(
    SELECT 1 FROM public.work_calendar_document_templates WHERE template_type = 'WORKING_SATURDAY'
);
