CREATE TABLE IF NOT EXISTS public.attendance_event_types
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(30) NOT NULL UNIQUE,
    name_th             VARCHAR(200) NOT NULL,
    name_en             VARCHAR(200),
    counts_as_work_time BOOLEAN NOT NULL DEFAULT FALSE,
    display_order       INTEGER NOT NULL DEFAULT 0,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_attendance_event_type_code CHECK (code <> ''),
    CONSTRAINT ck_attendance_event_type_display_order CHECK (display_order >= 0)
);

INSERT INTO public.attendance_event_types
    (code, name_th, name_en, counts_as_work_time, display_order, is_active)
VALUES
    ('WORK_FROM_HOME', 'Work from home', 'Work from home', TRUE, 10, TRUE),
    ('CUSTOMER_VISIT', 'ไปหาลูกค้า', 'Customer visit', TRUE, 20, TRUE),
    ('OTHER', 'อื่น ๆ', 'Other', FALSE, 30, TRUE)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.attendance_calendar_events
    DROP CONSTRAINT IF EXISTS ck_attendance_calendar_event_type;

ALTER TABLE public.attendance_calendar_events
    DROP CONSTRAINT IF EXISTS fk_attendance_calendar_event_type;

ALTER TABLE public.attendance_calendar_events
    ADD CONSTRAINT fk_attendance_calendar_event_type
    FOREIGN KEY (event_type) REFERENCES public.attendance_event_types(code)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION public.set_attendance_event_type_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_attendance_event_types_updated_at
    ON public.attendance_event_types;
CREATE TRIGGER trg_attendance_event_types_updated_at
BEFORE UPDATE ON public.attendance_event_types
FOR EACH ROW EXECUTE FUNCTION public.set_attendance_event_type_updated_at();

CREATE OR REPLACE FUNCTION public.queue_attendance_recalculation_from_event_type()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.counts_as_work_time IS DISTINCT FROM NEW.counts_as_work_time THEN
        INSERT INTO public.attendance_recalculation_queue(employee_id, work_date, reason)
        SELECT DISTINCT event.employee_id, event.event_date, 'ATTENDANCE_EVENT_TYPE_CHANGED'
        FROM public.attendance_calendar_events event
        WHERE event.event_type = NEW.code
        ON CONFLICT (employee_id, work_date) DO UPDATE
        SET reason = EXCLUDED.reason,
            requested_at = CURRENT_TIMESTAMP,
            attempts = 0,
            last_error = NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_attendance_event_type_recalculation
    ON public.attendance_event_types;
CREATE TRIGGER trg_attendance_event_type_recalculation
AFTER UPDATE OF counts_as_work_time ON public.attendance_event_types
FOR EACH ROW EXECUTE FUNCTION public.queue_attendance_recalculation_from_event_type();
