BEGIN;

CREATE TABLE IF NOT EXISTS public.pre_employees
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system         VARCHAR(100),
    source_reference_id   VARCHAR(200),
    source_payload        JSONB,
    employee_code         VARCHAR(50),
    title                 VARCHAR(50),
    first_name_th         VARCHAR(200),
    last_name_th          VARCHAR(200),
    full_name_en          VARCHAR(300),
    nickname              VARCHAR(100),
    email_address         VARCHAR(320),
    email_alias           VARCHAR(320),
    personal_mobile       VARCHAR(100),
    company_name          VARCHAR(200),
    business_unit         VARCHAR(200),
    department            VARCHAR(200),
    position_name         VARCHAR(200),
    start_date            DATE,
    supervisor_name       VARCHAR(300),
    leave_approver_name   VARCHAR(300),
    employment_type       VARCHAR(200),
    work_location         VARCHAR(300),
    status                VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    validation_message    TEXT,
    created_employee_id   BIGINT REFERENCES public.employees(id) ON DELETE RESTRICT,
    imported_by           VARCHAR(50),
    imported_by_name      VARCHAR(200),
    imported_at           TIMESTAMPTZ,
    reviewed_by           VARCHAR(50),
    reviewed_by_name      VARCHAR(200),
    reviewed_at           TIMESTAMPTZ,
    created_by            VARCHAR(50) NOT NULL,
    created_by_name       VARCHAR(200) NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    converted_by          VARCHAR(50),
    converted_by_name     VARCHAR(200),
    converted_at          TIMESTAMPTZ,
    CONSTRAINT ck_pre_employee_status CHECK
        (status IN ('DRAFT','INCOMPLETE','READY','CONVERTED','CANCELLED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pre_employees_source_reference
    ON public.pre_employees(source_system, source_reference_id)
    WHERE source_system IS NOT NULL AND source_reference_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_pre_employees_status_created
    ON public.pre_employees(status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_pre_employees_employee_code
    ON public.pre_employees(employee_code);

DROP TRIGGER IF EXISTS trg_pre_employees_updated_at ON public.pre_employees;
CREATE TRIGGER trg_pre_employees_updated_at
BEFORE UPDATE ON public.pre_employees
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

WITH action_seed(action_key, action_name, description, display_order) AS
(
    VALUES
        ('EDIT', 'แก้ไข Pre-Employee', 'ตรวจสอบและกรอกข้อมูล Pre-Employee', 10),
        ('CONVERT', 'สร้างพนักงาน', 'สร้างข้อมูล Employee จาก Pre-Employee ที่ตรวจสอบแล้ว', 20)
)
INSERT INTO public.application_page_actions
    (application_page_id, action_key, action_name, description, display_order)
SELECT page.id, seed.action_key, seed.action_name, seed.description, seed.display_order
FROM action_seed seed
JOIN public.application_pages page ON page.page_key = 'PRE_EMPLOYEES'
ON CONFLICT (application_page_id, action_key) DO UPDATE SET
    action_name = EXCLUDED.action_name,
    description = EXCLUDED.description,
    display_order = EXCLUDED.display_order,
    is_active = TRUE;

INSERT INTO public.employee_page_permissions
    (employee_id, application_page_id, can_access, updated_by, updated_by_name)
SELECT permission.employee_id, target.id, permission.can_access,
       permission.updated_by, permission.updated_by_name
FROM public.employee_page_permissions permission
JOIN public.application_pages source ON source.id = permission.application_page_id AND source.page_key = 'EMPLOYEES'
CROSS JOIN public.application_pages target
WHERE target.page_key = 'PRE_EMPLOYEES'
ON CONFLICT (employee_id, application_page_id) DO NOTHING;

INSERT INTO public.app_role_page_permissions
    (app_role_id, application_page_id, can_access, updated_by, updated_by_name)
SELECT permission.app_role_id, target.id, permission.can_access,
       permission.updated_by, permission.updated_by_name
FROM public.app_role_page_permissions permission
JOIN public.application_pages source ON source.id = permission.application_page_id AND source.page_key = 'EMPLOYEES'
CROSS JOIN public.application_pages target
WHERE target.page_key = 'PRE_EMPLOYEES'
ON CONFLICT (app_role_id, application_page_id) DO NOTHING;

INSERT INTO public.employee_page_action_permissions
    (employee_id, application_page_action_id, can_execute, updated_by, updated_by_name)
SELECT permission.employee_id, target_action.id, permission.can_execute,
       permission.updated_by, permission.updated_by_name
FROM public.employee_page_action_permissions permission
JOIN public.application_page_actions source_action ON source_action.id = permission.application_page_action_id
JOIN public.application_pages source_page ON source_page.id = source_action.application_page_id AND source_page.page_key = 'EMPLOYEES'
JOIN public.application_pages target_page ON target_page.page_key = 'PRE_EMPLOYEES'
JOIN public.application_page_actions target_action ON target_action.application_page_id = target_page.id
  AND target_action.action_key = CASE source_action.action_key WHEN 'CREATE' THEN 'CONVERT' WHEN 'EDIT' THEN 'EDIT' END
WHERE source_action.action_key IN ('CREATE','EDIT')
ON CONFLICT (employee_id, application_page_action_id) DO NOTHING;

INSERT INTO public.app_role_page_action_permissions
    (app_role_id, application_page_action_id, can_execute, updated_by, updated_by_name)
SELECT permission.app_role_id, target_action.id, permission.can_execute,
       permission.updated_by, permission.updated_by_name
FROM public.app_role_page_action_permissions permission
JOIN public.application_page_actions source_action ON source_action.id = permission.application_page_action_id
JOIN public.application_pages source_page ON source_page.id = source_action.application_page_id AND source_page.page_key = 'EMPLOYEES'
JOIN public.application_pages target_page ON target_page.page_key = 'PRE_EMPLOYEES'
JOIN public.application_page_actions target_action ON target_action.application_page_id = target_page.id
  AND target_action.action_key = CASE source_action.action_key WHEN 'CREATE' THEN 'CONVERT' WHEN 'EDIT' THEN 'EDIT' END
WHERE source_action.action_key IN ('CREATE','EDIT')
ON CONFLICT (app_role_id, application_page_action_id) DO NOTHING;

COMMIT;
