BEGIN;

CREATE TABLE IF NOT EXISTS public.lotus_notes_employee_outbox
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pre_employee_id     BIGINT       NOT NULL REFERENCES public.pre_employees(id),
    employee_id         BIGINT       NOT NULL REFERENCES public.employees(id),
    employee_code       VARCHAR(50)  NOT NULL,
    employee_name       VARCHAR(300) NOT NULL DEFAULT '',
    database_name       VARCHAR(100) NOT NULL,
    external_key        VARCHAR(100) NOT NULL,
    payload             JSONB        NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    attempt_count       INTEGER      NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_attempt_at     TIMESTAMPTZ,
    succeeded_at        TIMESTAMPTZ,
    last_error          TEXT,
    response_summary    TEXT,
    retry_requested_at  TIMESTAMPTZ,
    retry_requested_by  VARCHAR(100),
    retry_requested_name VARCHAR(300),
    CONSTRAINT ck_lotus_notes_employee_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ux_lotus_notes_employee_outbox_pre_employee UNIQUE(pre_employee_id)
);

CREATE INDEX IF NOT EXISTS ix_lotus_notes_employee_outbox_pending
    ON public.lotus_notes_employee_outbox(status, created_at, id);
CREATE INDEX IF NOT EXISTS ix_lotus_notes_employee_outbox_employee
    ON public.lotus_notes_employee_outbox(employee_code, created_at DESC);

INSERT INTO public.application_pages
    (page_key, page_name, route_path, category_name, display_order, is_active, is_enabled)
VALUES
    ('LOTUS_NOTES_EMPLOYEE_SYNC', 'ติดตามการส่งพนักงานไป Lotus Notes',
     '/system/lotus-notes-sync', 'การจัดการระบบ', 113, TRUE, TRUE)
ON CONFLICT (page_key) DO UPDATE SET
    page_name = EXCLUDED.page_name,
    route_path = EXCLUDED.route_path,
    category_name = EXCLUDED.category_name,
    display_order = EXCLUDED.display_order,
    is_active = TRUE;

INSERT INTO public.application_page_actions
    (application_page_id, action_key, action_name, description, display_order, is_active)
SELECT page.id, 'RETRY', 'ส่งซ้ำไป Lotus Notes',
       'นำรายการที่ส่งไม่สำเร็จกลับเข้าคิวเพื่อส่งใหม่โดยผู้ดูแล', 10, TRUE
FROM public.application_pages page
WHERE page.page_key = 'LOTUS_NOTES_EMPLOYEE_SYNC'
ON CONFLICT (application_page_id, action_key) DO UPDATE SET
    action_name = EXCLUDED.action_name,
    description = EXCLUDED.description,
    display_order = EXCLUDED.display_order,
    is_active = TRUE;

-- No default grant: the menu remains hidden until access is explicitly assigned.
COMMIT;
